intrepidboats/apps/difference/urls.py
from django.conf.urls import url

from .views import SharedTestimonialCreateView, create_upload_ticket, complete_upload_ticket

urlpatterns = [
    url(r'^shared_testimonial/$', SharedTestimonialCreateView.as_view(), name="shared_testimonials"),
    url(r'^create_ticket/$', create_upload_ticket, name="create_ticket"),
    url(r'^complete_ticket/(?P<ticket_id>\w+)/$', complete_upload_ticket, name="complete_ticket"),
]

intrepidboats/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from decorator_include import decorator_include
from machina.app import board

from intrepidboats.apps.common.admin import UserAdmin
from intrepidboats.sitemap import SITEMAPS

admin.autodiscover()
admin.site.unregister(User)
admin.site.register(User, UserAdmin)

urlpatterns = [
    url(r'^404/$', TemplateView.as_view(template_name="404.html")),
    url(r'^403/$', TemplateView.as_view(template_name="403.html")),
    url(r'^500/$', TemplateView.as_view(template_name="500.html")),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^owners_portal/forum/', decorator_include(login_required, board.urls)),
    url(r'^owners_portal/', include("intrepidboats.apps.owners_portal.urls", namespace="owners_portal")),
    url(r'^intrepid-difference/', include('intrepidboats.apps.difference.urls', namespace="difference")),
    url(r'^contact/', include('intrepidboats.apps.contact.urls', namespace="contact")),
    url(r'', include('intrepidboats.apps.common.urls', namespace="common")),
    url('^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include("cms.urls")),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': SITEMAPS}, name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intrepidboats/apps/difference/models.py
import requests
from ckeditor.fields import RichTextField
from cms.models.pluginmodel import CMSPlugin
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.models import TimeStampedModel

from intrepidboats.libs.vimeo_video_upload.models import Builder


class IntrepidDifferenceSectionPlugin(CMSPlugin):
    title = models.CharField(max_length=200, verbose_name=_("Title"))
    section_text = RichTextField(verbose_name=_("Section Text"))

    def __str__(self):
        return self.title


class ImageWithTextPlugin(CMSPlugin):
    image = models.ImageField(upload_to='cms/', verbose_name=_("Image"))
    section_text = models.TextField(verbose_name=_("Section Text"), null=True, blank=True)

    def __str__(self):
        return self.section_text


class SharedTestimonialUploadInfo(TimeStampedModel):
    ticket_id = models.CharField(max_length=610, verbose_name=_("ticket id"))
    uri = models.CharField(max_length=255, verbose_name=_("uri"))
    upload_link_secure = models.CharField(max_length=610, verbose_name=_("upload link secure"))
    complete_uri = models.CharField(max_length=610, verbose_name=_("complete uri"))
    completed = models.BooleanField(default=False, verbose_name=_("completed"))
    vimeo_user = models.TextField(verbose_name=_("vimeo user"))

    class Meta:
        verbose_name = _("shared testimonial info")
        verbose_name_plural = _("shared testimonial info")

    def __str__(self):
        return 'Ticket id: %s' % self.ticket_id


class SharedTestimonial(TimeStampedModel):
    first_name = models.CharField(max_length=255, verbose_name=_("first name"))
    last_name = models.CharField(max_length=255, verbose_name=_("last name"))
    title = models.CharField(max_length=100, verbose_name=_("title"), blank=True, null=True)
    email = models.EmailField(verbose_name=_("email"))
    message = models.TextField(verbose_name=_("text"))
    file = models.FileField(upload_to="shared_testimonials/", verbose_name=_("file"), blank=True, null=True)
    video_id = models.CharField(max_length=127, blank=True, null=True, verbose_name=_("video id"))
    thumbnail = models.ImageField(verbose_name=_("thumbnail"), upload_to="owners_gallery/", blank=True, null=True)
    info = models.OneToOneField(SharedTestimonialUploadInfo, related_name="shared_testimonial",
                                verbose_name=_("upload information"), null=True, blank=True)

    class Meta:
        verbose_name = _("shared testimonial")
        verbose_name_plural = _("shared testimonials")

    # pylint:disable=E1136
    def __str__(self):
        return '{first_name} {last_name}, {title}: {message}'.format(
            first_name=self.first_name,
            last_name=self.last_name,
            title=self.title,
            message=self.message[:100] + '...' if len(self.message) > 100 else self.message
        )


class TestimonialPlugin(CMSPlugin):
    testimonial = models.ForeignKey(SharedTestimonial)

    def __str__(self):
        return str(self.testimonial)


class TestimonialVideoPlugin(CMSPlugin):
    movie_url = models.URLField(verbose_name=_('Movie URL'))

    def __str__(self):
        return self.movie_url

    def thumbnail_url(self):
        video_id = self.movie_url.split(sep='/')[-1]
        json_request = requests.get(url='https://vimeo.com/api/v2/video/{id}.json'.format(id=video_id))
        return json_request.json()[0]['thumbnail_large']


class SharedTestimonialInfoBuilder(Builder):
    def create_testimonial_info(self):
        data = self.create_ticket()
        return SharedTestimonialUploadInfo.objects.create(
            ticket_id=data['ticket_id'],
            uri=data['uri'],
            upload_link_secure=data['upload_link_secure'],
            complete_uri=data['complete_uri'],
            vimeo_user=data['user']
        )

    def get_instance(self, ticket_id, user):
        return SharedTestimonialUploadInfo.objects.get(ticket_id=ticket_id)

    def get_text_field_for(self, instance):
        return instance.shared_testimonial.message

    def set_video_id(self, instance, vimeo_video_id):
        instance.shared_testimonial.video_id = vimeo_video_id
        instance.shared_testimonial.save()

    def save_thumbnail(self, instance, filename, thumbnail_file):
        instance.shared_testimonial.thumbnail.save(filename, thumbnail_file)
        instance.shared_testimonial.save()

    def set_to_completed(self, instance):
        instance.completed = True

intrepidboats/apps/difference/views.py
from django.http import HttpResponse
from django.http import JsonResponse
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.decorators.http import require_http_methods, require_GET
from django.views.generic import CreateView

from intrepidboats.apps.difference.models import SharedTestimonial, SharedTestimonialUploadInfo, \
    SharedTestimonialInfoBuilder
from intrepidboats.apps.difference.utils import send_shared_testimonial_email, send_new_testimonial_video_uploaded_email


class SharedTestimonialCreateView(CreateView):
    model = SharedTestimonial
    template_name = "difference/shared_testimonials/_form.html"
    fields = ['first_name', "last_name", "title", "email", "file", "message"]
    success_message = _("Thank you!")

    def form_valid(self, form):
        testimonial = form.save(commit=False)
        if 'video' in form.cleaned_data['file'].content_type:
            testimonial.file = None
            testimonial.info = SharedTestimonialUploadInfo.objects.get(ticket_id=form.data['ticket-id'])
        testimonial.save()
        send_new_testimonial_video_uploaded_email(testimonial)
        send_shared_testimonial_email(testimonial, self.request.META['HTTP_HOST'])
        return HttpResponse(content=self.get_success_message(), status=201)

    def form_invalid(self, form):
        return JsonResponse(data=form.errors, status=422)

    def get_success_message(self):
        return self.success_message


@require_GET
def create_upload_ticket(request):
    builder = SharedTestimonialInfoBuilder.default()
    testimonial_info = builder.create_testimonial_info()

    data = {
        "upload_link_secure": testimonial_info.upload_link_secure,
        "complete_path": reverse("difference:complete_ticket", kwargs={"ticket_id": testimonial_info.ticket_id}),
        "ticket_id": testimonial_info.ticket_id
    }
    return JsonResponse(data=data)


@require_http_methods(request_method_list=["PUT"])
def complete_upload_ticket(request, ticket_id):
    builder = SharedTestimonialInfoBuilder.default()
    builder.finish_upload(ticket_id=ticket_id)

    return JsonResponse(data={})

intrepidboats/apps/difference/templates/mobile/difference/tabs/about.html
{% load cms_tags static i18n sekizai_tags %}

<div role="tabpanel" class="tab-pane fade tab-testimonials" id="about">
  <div class="main">
    <div class="main-content">
      <div class="text-center pl4 pr4">
        {% placeholder "About Text" %}
      </div>
      <hr />
      <h3 class="text-uppercase">{% trans "owner privileges" %}</h3>

      <div>
        {% placeholder "Owner Privileges Image" %}
        <p>{% placeholder "Owner Privileges Text" %}</p>
        <div class="text-center">
          <img src="{% static "difference/images/intrepid-powerboats-green.svg" %}" class="img-responsive img-signature">
        </div>
      </div>

      <hr />
      <h3 class="text-uppercase">{% trans "testimonials" %}</h3>
      <div class="gradient"></div>

      <ul class="bxslider" id="slider-testimonials">
        {% placeholder "Testimonials" %}
      </ul>

      <div class="gradient bottom"></div>

      <div class="row mt2">
        <div class="col-sm-8">
          <div class="dropup">
            <a href="{% url "difference:create_ticket" %}" type="button" class="text-uppercase" id="share-button">
              {% trans "share your testimonial with us" %}
            </a>
            <div class="dropdown-menu form-testimonial">
              <span class="button close dark close-button" id="close-dropdown"></span>
              <p class="text-uppercase"><strong>{% trans "Share your testimonial with us" %}</strong></p>
              <p>{% trans "Let us know what you think of your Intrepid!" %}</p>
                {% include "difference/shared_testimonials/form.html" %}
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

intrepidboats/apps/difference/templates/mobile/difference/tabs/craftmanship.html
{% load cms_tags static i18n %}

<div role="tabpanel" class="tab-pane fade tab-craftsmanship" id="craftsmanship">

  <div class="header-image">
    <img src="{% static "difference/images/header-craftmanship-mobile.jpg" %}" class="img-responsive">
  </div>

  <div class="main">
    <div class="main-content">

      {% placeholder "Craftmanship (Left column)" %}
      {% placeholder "Craftmanship (Right column)" %}

    </div>
  </div>
</div>

intrepidboats/apps/difference/templates/mobile/difference/tabs/one_of_a_kind.html
{% load cms_tags static i18n %}

<div role="tabpanel" class="tab-pane fade" id="one-of-a-kind">

    <div class="header-image">
        <img src="{% static "difference/images/header-one-of-a-kind-mobile.jpg"  %}" class="img-responsive">
    </div>

    <div class="main">
        <div class="main-content">

            {% placeholder "One of a kind (Left column)" %}
            {% placeholder "One of a kind (Right column)" %}

            <div class="mt2">
                <ul class="bxslider text-overlay" id="slider-one-of-a-kind">
                    {% placeholder "One of a kind (Slider image)" %}
                </ul>
            </div>
        </div>
    </div>
</div>

intrepidboats/apps/difference/templates/mobile/difference/tabs/versatility.html
{% load cms_tags static i18n %}

<div role="tabpanel" class="tab-pane fade tab-versatility" id="versatility">

  <div class="header-image">
    <img src="{% static "difference/images/header-versatility-mobile.jpg" %}" class="img-responsive">
  </div>

  <div class="main">
    <div class="main-content">

      {% placeholder "Versatility (Left column)" %}
      {% placeholder "Versatility (Right column)" %}

    </div>
  </div>
</div>