intrepidboats/apps/owners_portal/urls.py
from django.conf.urls import url

from .views import DashboardView, create_upload_ticket, complete_upload_ticket, StepFeedbackCreateView, \
    change_notification, EditBoatNameView, AccountSettingsView, UploadPictureView, GalleryView, get_slide

urlpatterns = [
    url(r'^$', DashboardView.as_view(), name="owners_portal"),
    url(r'^gallery/$', GalleryView.as_view(), name="gallery"),
    url(r'^create_ticket/$', create_upload_ticket, name="create_ticket"),
    url(r'^complete_ticket/(?P<ticket_id>\w+)/$', complete_upload_ticket, name="complete_ticket"),
    url(r'^upload_picture/$', UploadPictureView.as_view(), name="upload_picture"),

    # Ajax!
    url(r'^steps/(?P<pk>\d+)/feedback/$', StepFeedbackCreateView.as_view(), name="step_feedback"),
    url(r'^edit_boat_name/(?P<pk>\d+)/$', EditBoatNameView.as_view(), name="edit_boat_name"),
    url(r'^account_settings/(?P<pk>\d+)/$', AccountSettingsView.as_view(), name="account_settings"),
    url(r'^steps/(?P<step_pk>\d+)/notify_change/$', change_notification, name="change_notification"),
    url(r'^get_slide/(?P<media_id>\d+)/$', get_slide, name="get_slide"),
]

intrepidboats/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from decorator_include import decorator_include
from machina.app import board

from intrepidboats.apps.common.admin import UserAdmin
from intrepidboats.sitemap import SITEMAPS

admin.autodiscover()
admin.site.unregister(User)
admin.site.register(User, UserAdmin)

urlpatterns = [
    url(r'^404/$', TemplateView.as_view(template_name="404.html")),
    url(r'^403/$', TemplateView.as_view(template_name="403.html")),
    url(r'^500/$', TemplateView.as_view(template_name="500.html")),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^owners_portal/forum/', decorator_include(login_required, board.urls)),
    url(r'^owners_portal/', include("intrepidboats.apps.owners_portal.urls", namespace="owners_portal")),
    url(r'^intrepid-difference/', include('intrepidboats.apps.difference.urls', namespace="difference")),
    url(r'^contact/', include('intrepidboats.apps.contact.urls', namespace="contact")),
    url(r'', include('intrepidboats.apps.common.urls', namespace="common")),
    url('^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include("cms.urls")),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': SITEMAPS}, name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intrepidboats/apps/owners_portal/forms.py
from django import forms

from intrepidboats.apps.common.models import ExtraUserData
from .models import SharedPicture


class SharedPictureForm(forms.ModelForm):
    class Meta:
        model = SharedPicture
        fields = ['comment', 'is_public', 'image', ]
        widgets = {
            'is_public': forms.RadioSelect
        }


class AccountSettingsForm(forms.ModelForm):
    class Meta:
        model = ExtraUserData
        fields = ['profile_picture', 'gallery_header']

    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

intrepidboats/apps/owners_portal/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.models import Site
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_POST, require_http_methods
from django.views.generic import CreateView, UpdateView
from django.views.generic import TemplateView, RedirectView

from intrepidboats.apps.common.models import ExtraUserData
from intrepidboats.apps.common.utils import split_queryset
from intrepidboats.apps.contact.views import SendInformationFormInvalidMixin
from .forms import SharedPictureForm, AccountSettingsForm
from .models import SharedVideoBuilder, StepFeedback, BoatStep, UserBoat, SharedPicture, SharedMedia, Survey
from .utils import send_report_email, send_step_feedback_email


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "owners_portal/index.html"

    def get_context_data(self, **kwargs):

        if self.request.user.is_authenticated():
            my_stuff = self.get_gallery({'uploader': self.request.user})
            profile, _ = ExtraUserData.objects.get_or_create(user=self.request.user)
        else:
            my_stuff = None
            profile = None
        # get a random survey, if any
        survey = Survey.objects.filter(enabled=True).order_by('?').first()
        return super().get_context_data(
            last_boat=self.get_last_boat(),
            my_stuff=my_stuff,
            community_shares=self.get_gallery({'is_public': True, 'is_approved': True}),
            share_picture_form=SharedPictureForm(),
            current_site=Site.objects.get_current().domain,
            profile=profile,
            survey=survey,
            **kwargs
        )

    def get_last_boat(self):
        if self.request.user.is_authenticated() and self.request.user.user_boats.count() > 0:
            return self.request.user.user_boats.prefetch_related("steps__assets").last()
        else:
            return None

    def get_gallery(self, attrs):
        gallery = SharedMedia.objects.media_content(attrs=attrs)
        return split_queryset(gallery, 10)


class GalleryView(LoginRequiredMixin, RedirectView):
    pattern_name = 'owners_portal:owners_portal'

    def get_redirect_url(self, *args, **kwargs):
        return super().get_redirect_url(*args, **kwargs) + '#gallery'


class EditBoatNameView(LoginRequiredMixin, UpdateView):
    success_url = '/'
    model = UserBoat
    fields = ['name']

    def form_valid(self, form):
        super().form_valid(form)
        return JsonResponse({'new_name': self.object.name})


class AccountSettingsView(LoginRequiredMixin, SendInformationFormInvalidMixin, UpdateView):
    model = ExtraUserData
    form_class = AccountSettingsForm
    template_name = 'owners_portal/partials/account_settings_form.html'
    success_url = reverse_lazy('owners_portal:owners_portal')

    def form_valid(self, form):
        if form.cleaned_data['first_name']:
            self.request.user.first_name = form.cleaned_data['first_name']
        if form.cleaned_data['last_name']:
            self.request.user.last_name = form.cleaned_data['last_name']
        self.request.user.save()
        return super().form_valid(form)


class UploadPictureView(LoginRequiredMixin, CreateView):
    model = SharedPicture
    form_class = SharedPictureForm
    template_name = 'owners_portal/partials/gallery_picture_form.html'

    def get_success_url(self):
        return reverse('owners_portal:owners_portal') + '#gallery'

    def form_invalid(self, form):
        super().form_invalid(form)
        return JsonResponse(form.errors, status=400)

    def form_valid(self, form):
        form.instance.uploader = self.request.user
        form.is_approved = False
        messages.add_message(self.request, messages.SUCCESS, _('Success! Your item has been uploaded'))
        return super().form_valid(form)


@login_required
@staff_member_required
@require_POST
def change_notification(request, step_pk):
    step = get_object_or_404(BoatStep, pk=step_pk)
    send_report_email(step.user_boat)
    return JsonResponse(data={}, status=200)


class StepFeedbackCreateView(LoginRequiredMixin, CreateView):
    model = StepFeedback
    fields = ('comments',)
    object = None

    def get_context_data(self, **kwargs):
        return super(StepFeedbackCreateView, self).get_context_data(step=self.get_step(), **kwargs)

    def form_valid(self, form):
        feedback = form.instance
        feedback.user = self.request.user
        feedback.step = self.get_step()
        self.object = form.save()
        send_step_feedback_email(self.object)
        return JsonResponse({"ok": True, "message": _("Thank you!")}, status=201)

    def get_step(self):
        return BoatStep.objects.for_user(self.request.user).get(pk=self.kwargs['pk'])

    def get_initial(self):
        return {
            "user": self.request.user,
            "step_id": self.get_step().pk
        }


@require_POST
@login_required
@ensure_csrf_cookie
def create_upload_ticket(request):
    builder = SharedVideoBuilder.default()
    form_data = dict(request.POST)

    video = builder.create_video(
        request.user,
        comment=form_data['comment'][0],
        is_public=(form_data['is_public'][0] == 'True'),
    )

    data = {
        "upload_link_secure": video.upload_link_secure,
        "complete_path": reverse("owners_portal:complete_ticket", kwargs={"ticket_id": video.ticket_id})
    }
    return JsonResponse(data=data)


@require_http_methods(request_method_list=["PUT"])
@login_required
def complete_upload_ticket(request, ticket_id):
    builder = SharedVideoBuilder.default()
    builder.finish_upload(ticket_id=ticket_id, user=request.user)
    builder.send_new_uploaded_video_email(ticket_id, request.user)
    messages.add_message(request, messages.SUCCESS, _('Success! Your item has been uploaded'))
    return JsonResponse(data={})


def get_slide(request, media_id):
    gallery = SharedMedia.objects.media_content(attrs={'is_public': True, 'is_approved': True}).values_list('id',
                                                                                                            flat=True)
    galleries = split_queryset(gallery, 10)
    slide = None
    for index, sub_gallery in enumerate(galleries):
        if int(media_id) in sub_gallery:
            slide = index
            break
    return JsonResponse(data={'slide': slide, 'media_id': media_id})

intrepidboats/apps/owners_portal/templates/mobile/owners_portal/index.html
{% extends "mobile/common/mobile_base.html" %}
{% load staticfiles i18n sekizai_tags %}

{% if site_metadata.owners_portal_description %}
    {% block meta_description %}
        {{ site_metadata.owners_portal_description }}
    {% endblock %}
{% endif %}

{% if site_metadata.owners_portal_og_title %}
    {% block meta_og_title %}
        {{ site_metadata.owners_portal_og_title }}
    {% endblock %}
{% endif %}

{% if site_metadata.owners_portal_og_description %}
    {% block meta_og_description %}
        {{ site_metadata.owners_portal_og_description }}
    {% endblock %}
{% endif %}

{% block body_classes %}page owners-portal{% endblock body_classes %}
{% block section %}Owner's Portal - {% endblock %}
{% block content %}

  <div class="main">

    <header class="text-center section-nav">

      <h1 class="text-uppercase">{% trans "owner's portal" %}</h1>

      <div class="gradient">
        <ul class="nav nav-tabs" role='tablist'>
          <li role=presentation class=dropdown>
            <a href="#" class="dropdown-toggle" aria-controls='owners-tabs-contents' id='owners-tabs'
               data-toggle='dropdown'><h2>
              <span class="tab-title">{% trans "SELECT" %} </span>
              <span class="chevron-down" aria-hidden="true"></span>
            </h2></a>
            <ul class='dropdown-menu' aria-labelledby='owners-tabs' id='owners-tabs-contents'>

              <li><a href="#dashboard" aria-controls="dashboard" role="tab" data-toggle="tab" class="text-uppercase">
                {% trans "my dashboard" %}
              </a></li>

              <li><a href="{% url "forum:index" %}" aria-controls="forum" role="tab" class="text-uppercase">
                {% trans "forum" %}
              </a></li>

              <li><a href="#gallery" aria-controls="gallery" role="tab" data-toggle="tab">
                {% trans "gallery" %}
              </a></li>

            </ul>
          </li>
        </ul>
      </div>

    </header>
  </div>

    <div class="tab-content">

        {% include "owners_portal/partials/dashboard.html" %}

        {% include "owners_portal/partials/gallery.html" %}

    </div>

    {% include "owners_portal/partials/edit_boat_name_modal.html" %}

    {% addtoblock "js" %}
        <script src="{% static "js/custom/mobile_tabs_behaviour.js" %}"></script>
        <script src="{% static "js/custom/video_player.js" %}"></script>
        <script src="{% static "js/custom/video_element.js" %}"></script>
        <script src="{% static "owners_portal/js/common_gallery_presentation.js" %}"></script>
        <script src="{% static "mobile/owners_portal/js/gallery_presentation.js" %}"></script>
        <script src="{% static "owners_portal/js/gallery_video_uploading.js" %}"></script>
        <script src="{% static "owners_portal/js/dashboard.js" %}"></script>
        <script src="{% static "owners_portal/js/boat_name_change.js" %}"></script>
    {% endaddtoblock %}
    {% addtoblock "cdn_js" %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.1.1/ekko-lightbox.min.js"></script>
    {% endaddtoblock %}
    {% addtoblock "cdn_css" %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.1.1/ekko-lightbox.min.css" />
    {% endaddtoblock %}

{% endblock content %}

intrepidboats/apps/owners_portal/templates/mobile/owners_portal/stepfeedback_form.html
{% load i18n %}
<form method="post" class="form dark step-feedback-form" action="{% url "owners_portal:step_feedback" pk=step.pk %}">
    {% csrf_token %}
    <span class="comment-container">
    <label class="text-uppercase">{% trans "send us any feedback or questions" %}.</label>
    <textarea placeholder="{% trans "QUESTIONS OR COMMENTS" %}"
              name="comments"
              required="required"
              class="input"></textarea>
    </span>
    <div class="pull-right">
        <button type="submit" class="button primary text-capitalize">{% trans "submit" %}</button>
    </div>
</form>