intrepidboats/apps/common/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth.views import logout, password_reset_done, password_reset_confirm, password_reset_complete
from django.views.generic import TemplateView

from .views import HomeView, NewsletterSubmission, activate_lang, WhatIsNewView, ArticleDetailView, \
    EventsView, RegistrationView, password_reset, login_view

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^newsletter_subscribe/$', NewsletterSubmission.as_view(), name="newsletter"),
    url(r'^newsletter_success/$', TemplateView.as_view(template_name='newsletter_success.html'),
        name="newsletter_success"),
    url(r'^activate_lang/$', activate_lang, name="activate_lang"),
    url(r'^what-is-new/$', WhatIsNewView.as_view(), name='what-is-new'),
    url(r'^article/(?P<pk>\d+)/(?P<title>[\w-]+)$', ArticleDetailView.as_view(), name='article'),
    url(r'^events/$', EventsView.as_view(), name='events'),
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^register/$', RegistrationView.as_view(), name='register'),
    url(r'^register/done/$', TemplateView.as_view(template_name="registration/done.html"), name='register-done'),
    url(r'^password/reset/$', password_reset,
        {
            'template_name': 'password_reset/form.html',
            'email_template_name': 'password_reset/email.html',
            'subject_template_name': 'password_reset/subject.txt',
            'post_reset_redirect': 'common:password_reset_done',
            'from_email': settings.NO_REPLY_EMAIL,
        },
        name='password_reset'),
    url(r'^password/reset/done/$', password_reset_done,
        {
            'template_name': 'password_reset/done.html'
        },
        name="password_reset_done"),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        password_reset_confirm,
        {
            'template_name': 'password_reset/confirm.html',
            'post_reset_redirect': 'common:password_reset_complete',
        },
        name="password_reset_confirm"),
    url(r'^password/done/$', password_reset_complete,
        {
            'template_name': 'password_reset/complete.html'
        },
        name="password_reset_complete"),
    url(r'^terms_of_use/$', TemplateView.as_view(template_name="terms_of_use.html"), name='terms_of_use'),
]

intrepidboats/urls.py
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from decorator_include import decorator_include
from machina.app import board

from intrepidboats.apps.common.admin import UserAdmin
from intrepidboats.sitemap import SITEMAPS

admin.autodiscover()
admin.site.unregister(User)
admin.site.register(User, UserAdmin)

urlpatterns = [
    url(r'^404/$', TemplateView.as_view(template_name="404.html")),
    url(r'^403/$', TemplateView.as_view(template_name="403.html")),
    url(r'^500/$', TemplateView.as_view(template_name="500.html")),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^owners_portal/forum/', decorator_include(login_required, board.urls)),
    url(r'^owners_portal/', include("intrepidboats.apps.owners_portal.urls", namespace="owners_portal")),
    url(r'^intrepid-difference/', include('intrepidboats.apps.difference.urls', namespace="difference")),
    url(r'^contact/', include('intrepidboats.apps.contact.urls', namespace="contact")),
    url(r'', include('intrepidboats.apps.common.urls', namespace="common")),
    url('^i18n/', include('django.conf.urls.i18n')),
    url(r'^', include("cms.urls")),

    url(r'^sitemap\.xml$', sitemap, {'sitemaps': SITEMAPS}, name='django.contrib.sitemaps.views.sitemap')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

intrepidboats/apps/common/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.utils.translation import ugettext as _
from nocaptcha_recaptcha.fields import NoReCaptchaField

from .models import NewsletterSubscriber


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = NewsletterSubscriber
        fields = ('first_name', 'last_name', 'email')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'input', 'placeholder': _('First name')}),
            'last_name': forms.TextInput(attrs={'class': 'input', 'placeholder': _('Last name')}),
            'email': forms.EmailInput(attrs={'class': 'input', 'placeholder': _('Email address')}),
        }


class UserRegistrationForm(ModelForm):
    password_repeat = forms.CharField(required=True, widget=forms.PasswordInput())
    email_repeat = forms.EmailField(required=True)
    phone = forms.CharField(required=False)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    fan = forms.BooleanField(required=False)
    intrepid_model = forms.CharField(required=False)
    intrepid_year = forms.CharField(required=False)
    intrepid_hull_id = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        is_mobile = kwargs.pop('request').flavour == 'mobile'
        super().__init__(*args, **kwargs)

    class Meta:
        model = User
        fields = ('email', 'password', 'username', 'first_name', 'last_name',)
        widgets = {
            'password': forms.PasswordInput(),
        }

    def clean_password(self):
        if self.data['password'] != self.data['password_repeat']:
            self.add_error('password', "Passwords don't match")
        return self.data['password']

    def clean(self):
        if self.data['email'] != self.data['email_repeat']:
            self.add_error('email', "Emails don't match")
        return super(UserRegistrationForm, self).clean()

intrepidboats/apps/common/views.py
import random

from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.views import login as django_login
from django.contrib.auth.views import password_reset as django_password_reset
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.translation import activate, check_for_language
from django.views.generic import TemplateView, CreateView, DetailView, FormView
from el_pagination.views import AjaxListView

from intrepidboats.apps.common.utils import send_successful_registration_emails, send_new_newsletter_subscriber_email, \
    send_new_registered_user_email
from .forms import NewsletterForm, UserRegistrationForm
from .models import PageSetting, NewsletterSubscriber, Article, Event, ExtraUserData


class HomeView(TemplateView):
    template_name = "home/index.html"
    HOME_PAGE_NAME = settings.HOME_PAGE_SETTINGS_NAME

    def get_context_data(self, **kwargs):
        page_setting = self.get_page_setting()
        page_assets = []
        if page_setting:
            page_assets = page_setting.random_assets(is_mobile=self.request.flavour == "mobile")
        return super(HomeView, self).get_context_data(
            page_setting=page_setting, page_assets=page_assets, newsletter_form=NewsletterForm())

    def get_page_setting(self):
        query_set = PageSetting.objects.filter(name=self.HOME_PAGE_NAME)
        if query_set.exists():
            return query_set.first()
        return None


class NewsletterSubmission(CreateView):
    model = NewsletterSubscriber
    form_class = NewsletterForm
    success_url = '/'  # TODO: unused url?

    def form_invalid(self, form):
        super().form_invalid(form)
        return JsonResponse(form.errors, status=400)

    def form_valid(self, form):
        super().form_valid(form)
        send_new_newsletter_subscriber_email(form)
        return JsonResponse({
            'success_page_url': reverse_lazy('common:newsletter_success'),
            'is_mobile': self.request.flavour == 'mobile',
        })


def activate_lang(request):
    lang = request.POST.get("language")
    check_for_language(lang)
    activate(language=lang)
    next_url = request.META.get('HTTP_REFERER')
    return redirect(next_url) if next_url else redirect('/')


class BlogPostDetailView(DetailView):
    pk_url_kwarg = 'pk'

    def get_context_data(self, **kwargs):
        context = super(BlogPostDetailView, self).get_context_data(**kwargs)
        posts = self.model.objects.exclude(id=self.object.id).filter(featured=True)
        posts_to_show_amount = 3 if posts.count() >= 3 else posts.count()
        context['sticky_posts'] = random.sample(set(posts), posts_to_show_amount)
        return context


class WhatIsNewView(AjaxListView):
    model = Article
    context_object_name = 'entry_list'
    template_name = 'blog_posts/what_is_new/whats_new.html'
    page_template = 'blog_posts/what_is_new/article_item.html'


class ArticleDetailView(BlogPostDetailView):
    model = Article
    template_name = 'blog_posts/what_is_new/article_detail.html'


class EventsView(AjaxListView):
    model = Event
    context_object_name = 'entry_list'
    template_name = 'blog_posts/events/events.html'
    page_template = 'blog_posts/events/event_item.html'

    def get_context_data(self, **kwargs):
        return super(EventsView, self).get_context_data(**kwargs)


class RegistrationView(FormView):
    form_class = UserRegistrationForm
    template_name = 'registration/register.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_success_url(self):
        return reverse('common:register-done')

    def form_valid(self, form):
        new_user = self.register(form)
        send_successful_registration_emails(form)
        send_new_registered_user_email(new_user, form)
        return HttpResponseRedirect(self.get_success_url())

    def register(self, form):
        new_user = User.objects.create_user(username=form.cleaned_data['username'],
                                            email=form.cleaned_data['email'],
                                            password=form.cleaned_data['password'], )
        new_user.first_name = form.cleaned_data['first_name']
        new_user.last_name = form.cleaned_data['last_name']
        new_user.save()
        ExtraUserData.objects.create(user=new_user, phone=form.cleaned_data['phone'], fan=form.cleaned_data['fan'],
                                    intrepid_model=form.cleaned_data['intrepid_model'],
                                    intrepid_year=form.cleaned_data['intrepid_year'],
                                    intrepid_hull_id=form.cleaned_data['intrepid_hull_id'])
        new_user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        login(self.request, new_user)
        return new_user


def password_reset(request, template_name, email_template_name, subject_template_name, post_reset_redirect, from_email):
    return django_password_reset(request, template_name=template_name, email_template_name=email_template_name,
                                 subject_template_name=subject_template_name, post_reset_redirect=post_reset_redirect,
                                 from_email=from_email, extra_email_context={'domain': request.META['HTTP_HOST']})


def login_view(*args):
    return django_login(*args, redirect_authenticated_user=True)

intrepidboats/apps/common/templates/mobile/password_reset/complete.html
{% extends "mobile/common/mobile_base.html" %}
{% load i18n %}
{% block section %}Recover your password - {% endblock %}
{% block content %}


  <div class="main">
    <p>{% trans 'Password changed successfully' %}</p>

    <p><a href="{% url 'common:login' %}">{% trans 'Log in' %}</a></p>
  </div>

{% endblock content %}

intrepidboats/apps/common/templates/mobile/password_reset/confirm.html
{% extends "mobile/common/mobile_base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block section %}Recover your password - {% endblock %}
{% block content %}
  <div class="main">
      <header class="text-center">
        <h1>OWNER’S PORTAL</h1>
        <div class="gradient"> </div>
      </header>
      <div class="login-container form">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">

                  {% if validlink %}

                    <h3>{% trans "Enter your new password twice" %}</h3>

                    <form method="post">{% csrf_token %}
                      {{ form.new_password1.errors }}
                      <p>{{ form.new_password1|attr:"placeholder:New password"|add_class:"input" }}</p>
                      {{ form.new_password2.errors }}
                      <p class="aligned wide">{{ form.new_password2|attr:"placeholder:Confirm password"|add_class:"input" }}</p>
                      <p class="text-right"><input type="submit" value='Change password' class="button primary" /></p>
                    </form>

                  {% else %}

                    <p>
                      {% trans "The password reset link is invalid, probably because it's already been used." %}
                      {% trans "Ask for another password reset link:" %}
                    </p>
                    <a href="{% url 'common:password_reset' %}">{% trans "Reset password" %}</a>

                  {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

intrepidboats/apps/common/templates/mobile/password_reset/done.html
{% extends "mobile/common/mobile_base.html" %}
{% load i18n %}
{% block section %}Recover your password - {% endblock %}
{% block content %}
    <div class="main">
      <header class="text-center">
        <h1>OWNER’S PORTAL</h1>
        <div class="gradient"> </div>
      </header>
      <div class="login-container form">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <h3>{% trans "Recover your password" %}</h3>

                    <p>
                        {% trans "We sent you an email with instructions on how to change your password. " %}
                        {% trans "You should receive it soon." %}
                    </p>

                    <p>
                        {% trans "If you don't get the email, make sure that you registered with that email address or check your spam folder." %}
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

intrepidboats/apps/common/templates/mobile/password_reset/form.html
{% extends "mobile/common/mobile_base.html" %}
{% load i18n %}
{% load widget_tweaks %}
{% block section %}Recover your password - {% endblock %}
{% block content %}
    <div class="navbar">
      <div class="main">
          {% include "common/components/language_dropdown.html" %}
      </div>
    </div>
    <div class="main">
      <header class="text-center">
        <h1>OWNER’S PORTAL</h1>
        <div class="gradient"> </div>
      </header>
      <div class="login-container form">
            <div class="row">
                <div class="col-sm-8 col-sm-offset-2">
                    <h3>{% trans "Recover your password" %}</h3>

                    <p>
                        {% trans "Enter your email address and we'll send you instructions " %}
                        {% trans "on how to get a new one." %}
                    </p>

                    {% if form.email.errors %}
                        <p>{% trans "Please enter a valid email address" %}</p>
                    {% endif %}
                </div>
            </div>
            <form method="post">{% csrf_token %}
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2">
                            {{ form.email|attr:"placeholder:Email address"|add_class:"input" }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-8 col-sm-offset-2 text-right">
                            <input type="submit" class="button primary mt2 mb2 tt-uppercase" value='RESET PASSWORD'/>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}